/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'productId' : bigint,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'model' : string,
  'inStock' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : bigint,
  'brand' : string,
  'price' : number,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCategory' : ActorMethod<[string, string], bigint>,
  'addInquiry' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addProduct' : ActorMethod<
    [string, string, number, bigint, string, bigint, string, string],
    bigint
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'filterProductsByPrice' : ActorMethod<[number, number], Array<Product>>,
  'getAllAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsPaged' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getCategory' : ActorMethod<[bigint], Category>,
  'getInquiriesForProduct' : ActorMethod<[bigint], Array<Inquiry>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[bigint], Array<Product>>,
  'getProductsByCategoryName' : ActorMethod<[string], Array<Product>>,
  'getTotalProducts' : ActorMethod<[], bigint>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, bigint, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];